ALTER TABLE users ALTER COLUMN street DROP NOT NULL;
ALTER TABLE users ALTER COLUMN neighborhood DROP NOT NULL;
ALTER TABLE users ALTER COLUMN city DROP NOT NULL;
ALTER TABLE users ALTER COLUMN state DROP NOT NULL;
ALTER TABLE users ALTER COLUMN postal_code DROP NOT NULL;
